name: 'EzChestShopReborn'
version: '${project.version}'
main: 'me.deadlight.ezchestshop.EzChestShop'
api-version: '1.21'
folia-supported: true
website: 'https://github.com/nouish/EzChestShop'
depend:
  - Vault
softdepend:
  - CoreProtect
  - WildChests
  - WorldGuard
  - Slimefun # In case just to load after the Slimefun
  - Multiverse-Core # Preventing null worlds
  - CMI
  - PlaceholderAPI
  - Towny
  - AdvancedRegionMarket
authors:
  - ItzAmirreza
  - ElitoGame
  - nouish
description: 'Easy Chest Shop that any server owner wants that for his/her players.'

commands:
  ecs:
    description: create or delete a shop
    aliases:
      - cs
      - cshop
      - chestshop
      - ezchestshop
  ecsadmin:
    description: commands designed for admins to moderate
  checkprofits:
    description: Check all your shop profits that you made offline!
    aliases:
      - cp

permissions:
  ecs.admin:
    description: Helper permission node to grant full shop admin access.
    children:
      ecs.admin.remove: true
      ecs.admin.reload: true
      ecs.admin.create: true
      ecs.admin.transfer: true
      ecs.admin.view: true
      ecs.checkprofits: true
      ecs.version.notify: true
  ecs.admin.remove:
    description: Controls access to remove others shops.
    default: op
  ecs.admin.reload:
    description: Controls access to reload plugin configuration.
    default: op
  ecs.admin.create:
    description: Controls access to create admin shop with infinite stock.
    default: op
  ecs.admin.transfer:
    description: Controls access to transfer ownership of a shop.
    default: op
  ecs.admin.view:
    description: Controls access to view shop stock as admin.
    default: op
  ecs.checkprofits:
    description: Controls access to check profits from your own shops.
    default: op
  ecs.version.notify:
    description: Toggle notification about plugin updates.
    default: op
